---
- name: Software installation
  hosts: servergroup
  become: yes  # To ensure the tasks are run with elevated privileges
  tasks:
    - name: Update the apt cache
      apt:
        update_cache: yes
        
    - name: Install nginx
      apt:
        name: nginx
        state: latest

    - name: Start nginx service
      service:
        name: nginx
        state: started
